### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by qwoeiuakjh** [opendreamnet/dreamtime#325]
**Describe the bug**

CONNECTION ERROR!
A problem has occurred when trying to get the information from Github, please make sure you have a stable internet connection and restart the application.

LogEvent: Github has returned that there are no releases!
    at Object._fetchReleases (file:///C:/Users/jm/AppData/Local/Programs/DreamTime/resources/app.asar/dist/assets/1575670.js:1:94148)
    at async Object.setup (file:///C:/Users/jm/AppData/Local/Programs/DreamTime/resources/app.asar/dist/assets/1575670.js:1:92911)
    at async Object.init (file:///C:/Users/jm/AppData/Local/Programs/DreamTime/resources/app.asar/dist/assets/1575670.js:1:17777)
    at async Promise.all (index 3)
    at async f (file:///C:/Users/jm/AppData/Local/Programs/DreamTime/resources/app.asar/dist/assets/1575670.js:1:19692)
    at async file:///C:/Users/jm/AppData/Local/Programs/DreamTime/resources/app.asar/dist/assets/1575670.js:1:20193
    at async t.a (file:///C:/Users/jm/AppData/Local/Programs/DreamTime/resources/app.asar/dist/assets/1575670.js:1:20079)
    at async file:///C:/Users/jm/AppData/Local/Programs/DreamTime/resources/app.asar/dist/assets/d662605.js:419:97170

my internet status is okay..  I cannot understand this situation.. 

Please help

**To Reproduce**

**Expected behavior**

**Screenshots**

**Enviroment (please complete the following information):**
 - DreamTime Version [e.g. 1.5.11]
 - OS: [e.g. Windows 10 1803]
 - RAM: [e.g. 8 GB]
 - CPU: [e.g. Ryzen 5 2600]
 - GPU: [e.g. RTX 2070 8 GB VRAM]

**Additional information**
Add any other information about the problem here.

**Comment by jworeth** [comment]
I am having the same error, same error logs
`LogEvent: Github has returned that there are no releases!
    at Object._fetchReleases (file:///C:/Program%20Files/Ivan%20Bravo%20Bravo/DreamTime/resources/app.asar/dist/assets/1575670.js:1:94148)
    at async Object.setup (file:///C:/Program%20Files/Ivan%20Bravo%20Bravo/DreamTime/resources/app.asar/dist/assets/1575670.js:1:92911)
    at async Object.init (file:///C:/Program%20Files/Ivan%20Bravo%20Bravo/DreamTime/resources/app.asar/dist/assets/1575670.js:1:17777)
    at async Promise.all (index 3)
    at async f (file:///C:/Program%20Files/Ivan%20Bravo%20Bravo/DreamTime/resources/app.asar/dist/assets/1575670.js:1:19692)
    at async file:///C:/Program%20Files/Ivan%20Bravo%20Bravo/DreamTime/resources/app.asar/dist/assets/1575670.js:1:20193
    at async t.a (file:///C:/Program%20Files/Ivan%20Bravo%20Bravo/DreamTime/resources/app.asar/dist/assets/1575670.js:1:20079)
    at async file:///C:/Program%20Files/Ivan%20Bravo%20Bravo/DreamTime/resources/app.asar/dist/assets/d662605.js:419:97170`

**Comment by Pathrom** [comment]
Me too the same problem

**Comment by Ishansharma303** [comment]
they terminated the program i guess

**Comment by Ashu11-A** [comment]
@qwoeiuakjh 
error is with api, install Checkpoints manually
File:
https://d.opendreamnet.com/v2/checkpoints/v0.0.1
and unzip into:
...\dreamtime\dreampower\

**Comment by kolessios** [comment]
I have fixed this problem, please re-open DreamTime.

Notice: DreamTime is no longer in development and any problems may take months to fix, to visit our new project that generates higher quality nudes visit [SukebeZone+](https://www.sukebezone.com).

**Comment by sevstep08** [comment]
im still havinge this issue
