### ISSUE TITLE
Connecction error

### ISSUE THREAD

**Issue by AlexEstu15** [opendreamnet/dreamtime#329]
Good night,
i was installing the dreamtime when i have the next error,

CONNECTION ERROR!
A problem has occurred when trying to get the information from Github, please make sure you have a stable internet connection and restart the application.

LogEvent: There is no Internet connection. Please make sure you are connected before starting.
    at Object.setup (file:///E:/Ivan%20Bravo%20Bravo/DreamTime/resources/app.asar/dist/assets/1575670.js:1:92663)
    at Object.setup (file:///E:/Ivan%20Bravo%20Bravo/DreamTime/resources/app.asar/dist/assets/1575670.js:1:98159)
    at async Object.init (file:///E:/Ivan%20Bravo%20Bravo/DreamTime/resources/app.asar/dist/assets/1575670.js:1:15827)
    at async Promise.all (index 1)
    at async f (file:///E:/Ivan%20Bravo%20Bravo/DreamTime/resources/app.asar/dist/assets/1575670.js:1:19692)
    at async file:///E:/Ivan%20Bravo%20Bravo/DreamTime/resources/app.asar/dist/assets/1575670.js:1:20193
    at async t.a (file:///E:/Ivan%20Bravo%20Bravo/DreamTime/resources/app.asar/dist/assets/1575670.js:1:20079)
    at async file:///E:/Ivan%20Bravo%20Bravo/DreamTime/resources/app.asar/dist/assets/d662605.js:419:97170

i dont know why becuse the connection to internet is good and to enter github i have no problem so... Any ideas to how fix this?

-AlexEstu15

**Comment by kolessios** [comment]
I have fixed this problem, please re-open DreamTime.

Notice: DreamTime is no longer in development and any problems may take months to fix, to visit our new project that generates higher quality nudes visit [SukebeZone+](https://www.sukebezone.com).
